### ISSUE TITLE
Oauth redirect_uri_mismatch

### ISSUE THREAD

**Issue by deveshmi** [jsifuentes/cq-source-googleworkspace#2]
When I run the cli on my mac - cloudquery sync source.yml destination_file.yml but the oauth fails with redirect_uri_mismatch. This is because the authorized redirect_uri has to be configured in Google credentials page but the URI that this source plugin chooses is has a port number which is selected ad-hoc.

**Comment by jsifuentes** [comment]
Hi @deveshmi. When creating your OAuth Client ID, make sure you create your OAuth Client ID as a "Desktop app" here:

<img width="619" alt="Screenshot 2024-01-15 at 12 12 16 PM" src="https://github.com/jsifuentes/cq-source-googleworkspace/assets/2856219/f07c8345-cc7f-4791-bb1d-8cb01345de38">

Then you should not experience an issue with redirect_uri mismatch. I will also make this clear in the README.

**Comment by jsifuentes** [comment]
Closing, but please reply if you experience another issue setting up your client ID.
